### ISSUE TITLE
Not work because of oder of MIDDLEWARE_CLASSES with GZipMiddleware

### ISSUE THREAD

**Issue by matinfo** [aldryn/aldryn-django-debug-toolbar#3]
Not work after installing in my Divio project. Because need placed after  GZipMiddleware in MIDDLEWARE_CLASSES settings.

**Workaround**: copy all middleware setup in MIDDLEWARE_CLASSES in settings.py and move `'debug_toolbar.middleware.DebugToolbarMiddleware'` defined at the beginning just after the middleware  `'django.middleware.gzip.GZipMiddleware'`.

**Comment by derek-adair** [comment]
It'd be awesome to get this fixed.... ;)

**Comment by derek-adair** [comment]
How would this even be solved tho?  I'm not sure how this addon is even adding this middleware class, i dont see it anywhere.

**Comment by evildmp** [comment]
@derek-adair There is a version 1.8.0.1 in the Alpha channel for testing.

**Comment by derek-adair** [comment]
Works for me!!

👍
